# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0d10b386a6a356aeb88abb733e933f9912cdf517857ac5c3669ad45cc87fcc61a073da4626ef0e21cc6c1df3d4e9ddef61cde8121e157fa4ac67d1acd010a9d

test:
  secret_key_base: ad1e43c71be6a6781cd0cac7813f8f607ac57ce805c03a4c285547190b0fdc8c6147e35886da04242b40025a94dd46bd3d6c69f893b89b955a0179624b65b5de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
